language: node_js
node_js:
  - 13.5.0

git:
  depth: 3
  quiet: yes

branches:
  except:
    - legacy
    - experimental

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn build
  - yarn test
