language: node_js
node_js:
  - 13.5.0

git:
  depth: 3
  quiet: yes

branches:
  except:
    - legacy
    - experimental

cache:
  yarn: true
  directories:
    - node_modules


install:
  - pip install poetry
  - yarn install
  - cd tests/e2e
  - poetry install
  - cd ../..

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - yarn build
  - yarn test
  - cd tests/e2e
  - poetry run behave

after_success:
  - bash <(curl -s https://codecov.io/bash)
